name: Regenerate json files for all add-ons

on:
  workflow_dispatch:

jobs:
  regenerateJson:
    permissions:
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.13 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Create validation errors file
      run: echo "" > validationErrors.md
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Regenerate json
      run: |
        validation/regenerateJson `
        --dir ..\addons `
        --output validationErrors.md
    - name: Commit & Push changes
      run: |
        git add addons
        if (git status --porcelain) {
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "[Automated] Regenerate json files"
          git pull --rebase
          git push
        } else {
          echo "No changes to commit; skipping commit and push."
        }
    - name: Upload validation errors as artifact
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: validationErrors
        path: validationErrors.md
  call-workflow:
    needs: regenerateJson
    uses: ./.github/workflows/transformDataToViews.yml
